module org.easytech.pelatologio {
    requires javafx.fxml;

    requires org.controlsfx.controls;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.bootstrapfx.core;
    requires java.xml.ws;
    requires java.xml.bind;
    requires javax.jws;
    requires com.fasterxml.jackson.databind;
    requires java.sql;
    requires org.seleniumhq.selenium.chrome_driver;
    requires org.seleniumhq.selenium.firefox_driver;
    requires org.seleniumhq.selenium.edge_driver;
    requires dev.failsafe.core;
    requires java.mail;
    requires com.calendarfx.view;
    requires javafx.swing;
    requires net.sf.jasperreports.core;
    requires sikulixapi;
    requires com.sun.jna.platform;
    requires com.sun.jna;
    requires org.seleniumhq.selenium.support;
    requires atlantafx.base;
    requires com.jfoenix;
    requires org.apache.commons.lang3;
    //requires org.mnode.ical4j.core;
    requires log4j;
    requires org.apache.httpcomponents.core5.httpcore5;
    requires jdk.httpserver;
    requires asterisk.java;
//    requires org.apache.poi.ooxml.schemas;
//    requires docx4j;
//    requires org.apache.poi.ooxml;

    opens org.easytech.pelatologio to javafx.fxml;
    exports org.easytech.pelatologio;
    exports org.easytech.pelatologio.models;
    opens org.easytech.pelatologio.models to javafx.fxml;
    exports org.easytech.pelatologio.helper;
    opens org.easytech.pelatologio.helper to javafx.fxml;
    exports org.easytech.pelatologio.accountants;
    opens org.easytech.pelatologio.accountants to javafx.fxml;
    exports org.easytech.pelatologio.customers;
    opens org.easytech.pelatologio.customers to javafx.fxml;
    exports org.easytech.pelatologio.devices;
    opens org.easytech.pelatologio.devices to javafx.fxml;
    exports org.easytech.pelatologio.items;
    opens org.easytech.pelatologio.items to javafx.fxml;
    exports org.easytech.pelatologio.logins;
    opens org.easytech.pelatologio.logins to javafx.fxml;
    exports org.easytech.pelatologio.offers;
    opens org.easytech.pelatologio.offers to javafx.fxml;
    exports org.easytech.pelatologio.orders;
    opens org.easytech.pelatologio.orders to javafx.fxml;
    exports org.easytech.pelatologio.subs;
    opens org.easytech.pelatologio.subs to javafx.fxml;
    exports org.easytech.pelatologio.suppliers;
    opens org.easytech.pelatologio.suppliers to javafx.fxml;
    exports org.easytech.pelatologio.tasks;
    opens org.easytech.pelatologio.tasks to javafx.fxml;
    exports org.easytech.pelatologio.applications;
    opens org.easytech.pelatologio.applications to javafx.fxml;
    exports org.easytech.pelatologio.settings;
    opens org.easytech.pelatologio.settings to javafx.fxml;
}